= Computer Architecture Course

== Setup Raspberry Pi OS

=== Compatible Devices

You will need at least a Raspberry Pi 3 or newer. +
This guide has been tested using a Raspberry Pi 4 (4GB) with a 16GB MicroSD. +
Notes on why the 64-bit installation is more tedious than common raspberry pi installations and only runs on beta software can be found https://pimylifeup.com/raspberry-pi-64-bit/[here].

[cols="1,1,1,1"]
|===
| *Model* | *Chip* | *Architecture* | *Compatible (in theory)*
| Pi 4 Model B   | BCM2711   | ARMv8 | ✅
| Pi 3 Model B+  | BCM2837B0 | ARMv8 | ✅
| Pi 3 Model A+  | BCM2837B0 | ARMv8 | ✅
| Pi 3 Model B   | BCM2837   | ARMv8 | ✅
| Pi 2 Model B   | BCM2836   | ARMv7 | ❌
| All Pi 1 Model | BCM2835   | ARMv6 | ❌
| Pi Zero        | BCM2835   | ARMv6 | ❌
|===

=== Download and flash SD card

https://downloads.raspberrypi.org/raspios_lite_arm64/images/[Download latest version here]

https://www.balena.io/etcher/[Use Balena Etcher to flash the img to a MicroSD]

Then, head to the root directory of the installation and create an empty file called `ssh` to activate ssh:

----
touch [...]/boot/ssh
----

=== Setup Raspberry Pi

- Log in using the default credentials `pi` & `raspberry`.

- Change the default password using `passwd`.

- Update the Pi: `sudo apt-get update && sudo apt-get upgrade`


=== Enable VNC server

Run `sudo raspi-config` and head to `3 Interface Options` > `P3 VNC` > _Enable it_

Install `lxsession`: `sudo apt-get install lxsession`

Then reboot: `sudo reboot`

You should now be able to login via VNC using https://www.realvnc.com/en/connect/download/viewer/[RealVNC Viewer]

- Modify the screen resolution to your liking: inline `-geometry 1920x1080` to the file `/etc/vnc/vncservice` (+ reboot for the changes to take affect)

=== Install course-specific packages

https://ilias.h-ka.de/ilias.php?ref_id=457199&cmdClass=ilobjforumgui&thr_pk=14705&cmd=viewThread&cmdNode=vj:mg&baseClass=ilrepositorygui[Ilias Source]

[source,bash]
----
sudo apt-get install -y firefox-esr gcc gdb openjdk-11-jdk openjdk-11-jre linux-perf
sudo apt-get install --reinstall build-essential
----

Following commands were omitted:

- `sudo apt install tightvncserver`: VNC server is already running
- `sudo apt install xfce4 xfce4-goodies`: Desktop environment which is already bundled with the raspberry pi
- `sudo netstat -tlnp`: Tries to map open ports on the machine to their corresponding processes
- `sun-java6*` was altered to `openjdk-11*` ( + `java6-bin` has been omitted)

=== Install Eclipse

[source,bash]
----
wget https://rhlx01.hs-esslingen.de/pub/Mirrors/eclipse/oomph/epp/2021-12/M1/eclipse-inst-jre-linux-aarch64.tar.gz
tar -zxvf eclipse-inst-jre-linux-aarch64.tar.gz
rm eclipse-inst-jre-linux-aarch64.tar.gz
cd eclipse-installer
export DISPLAY=:0.0 && ./eclipse-inst
----

=== Launch Eclipse

Select `Eclipse IDE for Embedded C/C++ Developers` and hit `Install`


=== Fetch the project

[source,bash]
----
sudo apt-get install -y git
git clone https://github.com/cedric-uden/rechnerarchitektur.git
----

Then open this in `Ecplise IDE for Embedded C`

=== Run the files

change directory to this git dir: e.g. `cd ~/rechnerarchitektur`

----
make ex01
./build/add_two_numbers
make ex02
./build/christmastree
----

== Cross-Compile the files from x86 Linux host

The assembler files can also be cross-compiled from any x86 host. +
To achieve this, simply install `gcc-aarch64-linux-gnu` and compile it using
its bundled `gcc`:

[source,bash]
----
sudo apt-get install gcc-aarch64-linux-gnu
aarch64-linux-gnu-gcc -mtune=cortex-a72 add_two_numbers0.s
----
