= Computer Architecture Course

== Setup Raspberry Pi OS

=== Compatible Devices

You will need a Raspeberry Pi 3 or newer. +
Testing conducted on a Raspberry Pi 4 (4GB)

[cols="1,1,1,1"]
|===
| *Model* | *Chip* | *Architecture* | *Compatible*
| Pi 4 Model B   | BCM2711   | ARMv8 | ✅
| Pi 3 Model B+  | BCM2837B0 | ARMv8 | ✅
| Pi 3 Model A+  | BCM2837B0 | ARMv8 | ✅
| Pi 3 Model B   | BCM2837   | ARMv8 | ✅
| Pi 2 Model B   | BCM2836   | ARMv7 | ❌
| All Pi 1 Model | BCM2835   | ARMv6 | ❌
| Pi Zero        | BCM2835   | ARMv6 | ❌
|===

=== Download and install

https://www.raspberrypi.com/software/operating-systems/[Download "Raspberry Pi OS with desktop"]

https://www.balena.io/etcher/[Use Balena Etcher to flash the img to a MicroSD]


+++ <details><summary> +++
Optional: setup `ssh` and wifi
+++ </summary><div> +++

- Add ssh: `touch [...]/boot/ssh`

- Add wifi: `vim [...]/boot/wpa_supplicant.conf` and fill with config:

[source,config]
----
country=DE
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
	ssid="WIFI_SSID"
	psk="WIFI_PASSWORD"
}
----
+++ </div></details> +++

=== Connect to Raspberry Pi

`ssh pi@pi-host-localip` and please change the password as promped by the shell with `passwd` :-).

Then, update the raspberry: `sudo apt-get update && sudo apt-get upgrade`

== Setup Raspberry Pi

=== Connect to VNC

Activate VNC Server:

- Enter `sudo raspi-config`

- Navigate to `3 Interface Options` > `P3 VNC` > `Yes` _to enable it_

- Navigate to `2 Display Options` > `D1 Resolution` > `1280x720` _or_ `1920x1080`

- Reboot the raspberry: `sudo reboot`

You should now be able to login to VNC Server using https://www.realvnc.com/en/connect/download/viewer/[RealVNC VNC Viewer].
Use the `pi` user and your password.


=== Install course-specific packages

==== From package manager

https://ilias.h-ka.de/ilias.php?ref_id=457199&cmdClass=ilobjforumgui&thr_pk=14705&cmd=viewThread&cmdNode=vj:mg&baseClass=ilrepositorygui[Ilias Source]

[source,bash]
----
sudo apt-get install -y firefox-esr gcc gdb openjdk-8-jdk openjdk-11-jre linux-perf
sudo apt-get install --reinstall build-essential
----

Following commands were omitted:

- `sudo apt install tightvncserver`: VNC server is already running
- `sudo apt install xfce4 xfce4-goodies`: Desktop environment which is already bundled with the raspberry pi
- `sudo netstat -tlnp`: Tries to map open ports on the machine to their corresponding processes
- `sun-java6*` was altered to `openjdk-8*` ( + `java6-bin` has been omitted)

==== Install eclipse

[source,bash]
----
wget https://rhlx01.hs-esslingen.de/pub/Mirrors/eclipse/oomph/epp/2021-12/M1/eclipse-inst-jre-linux-aarch64.tar.gz
tar -zxvf eclipse-inst-jre-linux-aarch64.tar.gz
rm eclipse-inst-jre-linux-aarch64.tar.gz
cd eclipse-installer
export DISPLAY=0.0 && ./eclipse-inst
----
